/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var geometry_index_pb = require('../geometry/index_pb.js');
var geometry_posn_pb = require('../geometry/posn_pb.js');
var geometry_item_pb = require('../geometry/item_pb.js');
goog.exportSymbol('proto.ProtobufHistory.AddHandleAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.DocAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.GroupAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.InitAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.InsertAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.InsertAction.ItemIndex', null, global);
goog.exportSymbol('proto.ProtobufHistory.NudgeAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.NudgeHandleAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.RemoveAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.RemoveAction.ItemIndex', null, global);
goog.exportSymbol('proto.ProtobufHistory.RemoveHandleAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.RotateAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.ScaleAction', null, global);
goog.exportSymbol('proto.ProtobufHistory.UngroupAction', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.DocAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ProtobufHistory.DocAction.oneofGroups_);
};
goog.inherits(proto.ProtobufHistory.DocAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.DocAction.displayName = 'proto.ProtobufHistory.DocAction';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ProtobufHistory.DocAction.oneofGroups_ = [[1,2,3,4,5,6,7,8,9,10,11]];

/**
 * @enum {number}
 */
proto.ProtobufHistory.DocAction.ActionCase = {
  ACTION_NOT_SET: 0,
  INITACTION: 1,
  NUDGEACTION: 2,
  SCALEACTION: 3,
  ROTATEACTION: 4,
  NUDGEHANDLEACTION: 5,
  ADDHANDLEACTION: 6,
  REMOVEHANDLEACTION: 7,
  INSERTACTION: 8,
  REMOVEACTION: 9,
  GROUPACTION: 10,
  UNGROUPACTION: 11
};

/**
 * @return {proto.ProtobufHistory.DocAction.ActionCase}
 */
proto.ProtobufHistory.DocAction.prototype.getActionCase = function() {
  return /** @type {proto.ProtobufHistory.DocAction.ActionCase} */(jspb.Message.computeOneofCase(this, proto.ProtobufHistory.DocAction.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.DocAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.DocAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.DocAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.DocAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    initaction: (f = msg.getInitaction()) && proto.ProtobufHistory.InitAction.toObject(includeInstance, f),
    nudgeaction: (f = msg.getNudgeaction()) && proto.ProtobufHistory.NudgeAction.toObject(includeInstance, f),
    scaleaction: (f = msg.getScaleaction()) && proto.ProtobufHistory.ScaleAction.toObject(includeInstance, f),
    rotateaction: (f = msg.getRotateaction()) && proto.ProtobufHistory.RotateAction.toObject(includeInstance, f),
    nudgehandleaction: (f = msg.getNudgehandleaction()) && proto.ProtobufHistory.NudgeHandleAction.toObject(includeInstance, f),
    addhandleaction: (f = msg.getAddhandleaction()) && proto.ProtobufHistory.AddHandleAction.toObject(includeInstance, f),
    removehandleaction: (f = msg.getRemovehandleaction()) && proto.ProtobufHistory.RemoveHandleAction.toObject(includeInstance, f),
    insertaction: (f = msg.getInsertaction()) && proto.ProtobufHistory.InsertAction.toObject(includeInstance, f),
    removeaction: (f = msg.getRemoveaction()) && proto.ProtobufHistory.RemoveAction.toObject(includeInstance, f),
    groupaction: (f = msg.getGroupaction()) && proto.ProtobufHistory.GroupAction.toObject(includeInstance, f),
    ungroupaction: (f = msg.getUngroupaction()) && proto.ProtobufHistory.UngroupAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.DocAction} The clone.
 */
proto.ProtobufHistory.DocAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.DocAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional InitAction initAction = 1;
 * @return {proto.ProtobufHistory.InitAction}
 */
proto.ProtobufHistory.DocAction.prototype.getInitaction = function() {
  return /** @type{proto.ProtobufHistory.InitAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.InitAction, 1));
};


/** @param {proto.ProtobufHistory.InitAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setInitaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearInitaction = function() {
  this.setInitaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasInitaction = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional NudgeAction nudgeAction = 2;
 * @return {proto.ProtobufHistory.NudgeAction}
 */
proto.ProtobufHistory.DocAction.prototype.getNudgeaction = function() {
  return /** @type{proto.ProtobufHistory.NudgeAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.NudgeAction, 2));
};


/** @param {proto.ProtobufHistory.NudgeAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setNudgeaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearNudgeaction = function() {
  this.setNudgeaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasNudgeaction = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ScaleAction scaleAction = 3;
 * @return {proto.ProtobufHistory.ScaleAction}
 */
proto.ProtobufHistory.DocAction.prototype.getScaleaction = function() {
  return /** @type{proto.ProtobufHistory.ScaleAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.ScaleAction, 3));
};


/** @param {proto.ProtobufHistory.ScaleAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setScaleaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearScaleaction = function() {
  this.setScaleaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasScaleaction = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional RotateAction rotateAction = 4;
 * @return {proto.ProtobufHistory.RotateAction}
 */
proto.ProtobufHistory.DocAction.prototype.getRotateaction = function() {
  return /** @type{proto.ProtobufHistory.RotateAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.RotateAction, 4));
};


/** @param {proto.ProtobufHistory.RotateAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setRotateaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearRotateaction = function() {
  this.setRotateaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasRotateaction = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional NudgeHandleAction nudgeHandleAction = 5;
 * @return {proto.ProtobufHistory.NudgeHandleAction}
 */
proto.ProtobufHistory.DocAction.prototype.getNudgehandleaction = function() {
  return /** @type{proto.ProtobufHistory.NudgeHandleAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.NudgeHandleAction, 5));
};


/** @param {proto.ProtobufHistory.NudgeHandleAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setNudgehandleaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearNudgehandleaction = function() {
  this.setNudgehandleaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasNudgehandleaction = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional AddHandleAction addHandleAction = 6;
 * @return {proto.ProtobufHistory.AddHandleAction}
 */
proto.ProtobufHistory.DocAction.prototype.getAddhandleaction = function() {
  return /** @type{proto.ProtobufHistory.AddHandleAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.AddHandleAction, 6));
};


/** @param {proto.ProtobufHistory.AddHandleAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setAddhandleaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearAddhandleaction = function() {
  this.setAddhandleaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasAddhandleaction = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional RemoveHandleAction removeHandleAction = 7;
 * @return {proto.ProtobufHistory.RemoveHandleAction}
 */
proto.ProtobufHistory.DocAction.prototype.getRemovehandleaction = function() {
  return /** @type{proto.ProtobufHistory.RemoveHandleAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.RemoveHandleAction, 7));
};


/** @param {proto.ProtobufHistory.RemoveHandleAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setRemovehandleaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearRemovehandleaction = function() {
  this.setRemovehandleaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasRemovehandleaction = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional InsertAction insertAction = 8;
 * @return {proto.ProtobufHistory.InsertAction}
 */
proto.ProtobufHistory.DocAction.prototype.getInsertaction = function() {
  return /** @type{proto.ProtobufHistory.InsertAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.InsertAction, 8));
};


/** @param {proto.ProtobufHistory.InsertAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setInsertaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearInsertaction = function() {
  this.setInsertaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasInsertaction = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional RemoveAction removeAction = 9;
 * @return {proto.ProtobufHistory.RemoveAction}
 */
proto.ProtobufHistory.DocAction.prototype.getRemoveaction = function() {
  return /** @type{proto.ProtobufHistory.RemoveAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.RemoveAction, 9));
};


/** @param {proto.ProtobufHistory.RemoveAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setRemoveaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearRemoveaction = function() {
  this.setRemoveaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasRemoveaction = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional GroupAction groupAction = 10;
 * @return {proto.ProtobufHistory.GroupAction}
 */
proto.ProtobufHistory.DocAction.prototype.getGroupaction = function() {
  return /** @type{proto.ProtobufHistory.GroupAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.GroupAction, 10));
};


/** @param {proto.ProtobufHistory.GroupAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setGroupaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearGroupaction = function() {
  this.setGroupaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasGroupaction = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional UngroupAction ungroupAction = 11;
 * @return {proto.ProtobufHistory.UngroupAction}
 */
proto.ProtobufHistory.DocAction.prototype.getUngroupaction = function() {
  return /** @type{proto.ProtobufHistory.UngroupAction} */ (
    jspb.Message.getWrapperField(this, proto.ProtobufHistory.UngroupAction, 11));
};


/** @param {proto.ProtobufHistory.UngroupAction|undefined} value  */
proto.ProtobufHistory.DocAction.prototype.setUngroupaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.ProtobufHistory.DocAction.oneofGroups_[0], value);
};


proto.ProtobufHistory.DocAction.prototype.clearUngroupaction = function() {
  this.setUngroupaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocAction.prototype.hasUngroupaction = function() {
  return jspb.Message.getField(this, 11) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.InitAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ProtobufHistory.InitAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.InitAction.displayName = 'proto.ProtobufHistory.InitAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.InitAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.InitAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.InitAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.InitAction.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.InitAction} The clone.
 */
proto.ProtobufHistory.InitAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.InitAction} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.NudgeAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.NudgeAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.NudgeAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.NudgeAction.displayName = 'proto.ProtobufHistory.NudgeAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.NudgeAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.NudgeAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.NudgeAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.NudgeAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.NudgeAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    indexesList: jspb.Message.toObjectList(msg.getIndexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    xd: msg.getXd(),
    yd: msg.getYd()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.NudgeAction} The clone.
 */
proto.ProtobufHistory.NudgeAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.NudgeAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index indexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.NudgeAction.prototype.getIndexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.NudgeAction.prototype.setIndexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.NudgeAction.prototype.clearIndexesList = function() {
  this.setIndexesList([]);
};


/**
 * optional double xd = 2;
 * @return {number}
 */
proto.ProtobufHistory.NudgeAction.prototype.getXd = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.ProtobufHistory.NudgeAction.prototype.setXd = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double yd = 3;
 * @return {number}
 */
proto.ProtobufHistory.NudgeAction.prototype.getYd = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.ProtobufHistory.NudgeAction.prototype.setYd = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.ScaleAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.ScaleAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.ScaleAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.ScaleAction.displayName = 'proto.ProtobufHistory.ScaleAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.ScaleAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.ScaleAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.ScaleAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.ScaleAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.ScaleAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    indexesList: jspb.Message.toObjectList(msg.getIndexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    xs: msg.getXs(),
    ys: msg.getYs(),
    origin: (f = msg.getOrigin()) && geometry_posn_pb.Posn.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.ScaleAction} The clone.
 */
proto.ProtobufHistory.ScaleAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.ScaleAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index indexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.ScaleAction.prototype.getIndexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.ScaleAction.prototype.setIndexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.ScaleAction.prototype.clearIndexesList = function() {
  this.setIndexesList([]);
};


/**
 * optional double xs = 2;
 * @return {number}
 */
proto.ProtobufHistory.ScaleAction.prototype.getXs = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.ProtobufHistory.ScaleAction.prototype.setXs = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double ys = 3;
 * @return {number}
 */
proto.ProtobufHistory.ScaleAction.prototype.getYs = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.ProtobufHistory.ScaleAction.prototype.setYs = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional Posn origin = 4;
 * @return {proto.Posn}
 */
proto.ProtobufHistory.ScaleAction.prototype.getOrigin = function() {
  return /** @type{proto.Posn} */ (
    jspb.Message.getWrapperField(this, geometry_posn_pb.Posn, 4));
};


/** @param {proto.Posn|undefined} value  */
proto.ProtobufHistory.ScaleAction.prototype.setOrigin = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.ProtobufHistory.ScaleAction.prototype.clearOrigin = function() {
  this.setOrigin(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.ScaleAction.prototype.hasOrigin = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.RotateAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.RotateAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.RotateAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.RotateAction.displayName = 'proto.ProtobufHistory.RotateAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.RotateAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.RotateAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.RotateAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.RotateAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.RotateAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    indexesList: jspb.Message.toObjectList(msg.getIndexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    angle: msg.getAngle(),
    origin: (f = msg.getOrigin()) && geometry_posn_pb.Posn.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.RotateAction} The clone.
 */
proto.ProtobufHistory.RotateAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.RotateAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index indexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.RotateAction.prototype.getIndexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.RotateAction.prototype.setIndexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.RotateAction.prototype.clearIndexesList = function() {
  this.setIndexesList([]);
};


/**
 * optional double angle = 2;
 * @return {number}
 */
proto.ProtobufHistory.RotateAction.prototype.getAngle = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.ProtobufHistory.RotateAction.prototype.setAngle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional Posn origin = 3;
 * @return {proto.Posn}
 */
proto.ProtobufHistory.RotateAction.prototype.getOrigin = function() {
  return /** @type{proto.Posn} */ (
    jspb.Message.getWrapperField(this, geometry_posn_pb.Posn, 3));
};


/** @param {proto.Posn|undefined} value  */
proto.ProtobufHistory.RotateAction.prototype.setOrigin = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.ProtobufHistory.RotateAction.prototype.clearOrigin = function() {
  this.setOrigin(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.RotateAction.prototype.hasOrigin = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.NudgeHandleAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.NudgeHandleAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.NudgeHandleAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.NudgeHandleAction.displayName = 'proto.ProtobufHistory.NudgeHandleAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.NudgeHandleAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.NudgeHandleAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.NudgeHandleAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.NudgeHandleAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.NudgeHandleAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    indexesList: jspb.Message.toObjectList(msg.getIndexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    xd: msg.getXd(),
    yd: msg.getYd(),
    handle: msg.getHandle()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.NudgeHandleAction} The clone.
 */
proto.ProtobufHistory.NudgeHandleAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.NudgeHandleAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index indexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.NudgeHandleAction.prototype.getIndexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.NudgeHandleAction.prototype.setIndexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.NudgeHandleAction.prototype.clearIndexesList = function() {
  this.setIndexesList([]);
};


/**
 * optional double xd = 2;
 * @return {number}
 */
proto.ProtobufHistory.NudgeHandleAction.prototype.getXd = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.ProtobufHistory.NudgeHandleAction.prototype.setXd = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double yd = 3;
 * @return {number}
 */
proto.ProtobufHistory.NudgeHandleAction.prototype.getYd = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.ProtobufHistory.NudgeHandleAction.prototype.setYd = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional Handle handle = 4;
 * @return {!proto.Handle}
 */
proto.ProtobufHistory.NudgeHandleAction.prototype.getHandle = function() {
  return /** @type {!proto.Handle} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {!proto.Handle} value  */
proto.ProtobufHistory.NudgeHandleAction.prototype.setHandle = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.AddHandleAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.AddHandleAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.AddHandleAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.AddHandleAction.displayName = 'proto.ProtobufHistory.AddHandleAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.AddHandleAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.AddHandleAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.AddHandleAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.AddHandleAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.AddHandleAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    indexesList: jspb.Message.toObjectList(msg.getIndexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    handle: msg.getHandle(),
    posn: (f = msg.getPosn()) && geometry_posn_pb.Posn.toObject(includeInstance, f),
    reflect: msg.getReflect()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.AddHandleAction} The clone.
 */
proto.ProtobufHistory.AddHandleAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.AddHandleAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index indexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.AddHandleAction.prototype.getIndexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.AddHandleAction.prototype.setIndexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.AddHandleAction.prototype.clearIndexesList = function() {
  this.setIndexesList([]);
};


/**
 * optional Handle handle = 2;
 * @return {!proto.Handle}
 */
proto.ProtobufHistory.AddHandleAction.prototype.getHandle = function() {
  return /** @type {!proto.Handle} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {!proto.Handle} value  */
proto.ProtobufHistory.AddHandleAction.prototype.setHandle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional Posn posn = 3;
 * @return {proto.Posn}
 */
proto.ProtobufHistory.AddHandleAction.prototype.getPosn = function() {
  return /** @type{proto.Posn} */ (
    jspb.Message.getWrapperField(this, geometry_posn_pb.Posn, 3));
};


/** @param {proto.Posn|undefined} value  */
proto.ProtobufHistory.AddHandleAction.prototype.setPosn = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.ProtobufHistory.AddHandleAction.prototype.clearPosn = function() {
  this.setPosn(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.AddHandleAction.prototype.hasPosn = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool reflect = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ProtobufHistory.AddHandleAction.prototype.getReflect = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 4, false));
};


/** @param {boolean} value  */
proto.ProtobufHistory.AddHandleAction.prototype.setReflect = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.RemoveHandleAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.RemoveHandleAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.RemoveHandleAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.RemoveHandleAction.displayName = 'proto.ProtobufHistory.RemoveHandleAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.RemoveHandleAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.RemoveHandleAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.RemoveHandleAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.RemoveHandleAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.RemoveHandleAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    indexesList: jspb.Message.toObjectList(msg.getIndexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    handle: msg.getHandle(),
    reflect: msg.getReflect()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.RemoveHandleAction} The clone.
 */
proto.ProtobufHistory.RemoveHandleAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.RemoveHandleAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index indexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.RemoveHandleAction.prototype.getIndexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.RemoveHandleAction.prototype.setIndexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.RemoveHandleAction.prototype.clearIndexesList = function() {
  this.setIndexesList([]);
};


/**
 * optional Handle handle = 2;
 * @return {!proto.Handle}
 */
proto.ProtobufHistory.RemoveHandleAction.prototype.getHandle = function() {
  return /** @type {!proto.Handle} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {!proto.Handle} value  */
proto.ProtobufHistory.RemoveHandleAction.prototype.setHandle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool reflect = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ProtobufHistory.RemoveHandleAction.prototype.getReflect = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 3, false));
};


/** @param {boolean} value  */
proto.ProtobufHistory.RemoveHandleAction.prototype.setReflect = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.InsertAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.InsertAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.InsertAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.InsertAction.displayName = 'proto.ProtobufHistory.InsertAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.InsertAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.InsertAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.InsertAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.InsertAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.InsertAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.ProtobufHistory.InsertAction.ItemIndex.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.InsertAction} The clone.
 */
proto.ProtobufHistory.InsertAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.InsertAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated ItemIndex items = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ProtobufHistory.InsertAction.ItemIndex>}
 */
proto.ProtobufHistory.InsertAction.prototype.getItemsList = function() {
  return /** @type{!Array.<!proto.ProtobufHistory.InsertAction.ItemIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ProtobufHistory.InsertAction.ItemIndex, 1));
};


/** @param {Array.<!proto.ProtobufHistory.InsertAction.ItemIndex>} value  */
proto.ProtobufHistory.InsertAction.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.InsertAction.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.InsertAction.ItemIndex = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ProtobufHistory.InsertAction.ItemIndex, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.InsertAction.ItemIndex.displayName = 'proto.ProtobufHistory.InsertAction.ItemIndex';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.InsertAction.ItemIndex.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.InsertAction.ItemIndex} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.InsertAction.ItemIndex.toObject = function(includeInstance, msg) {
  var f, obj = {
    item: (f = msg.getItem()) && geometry_item_pb.Item.toObject(includeInstance, f),
    index: (f = msg.getIndex()) && geometry_index_pb.Index.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.InsertAction.ItemIndex} The clone.
 */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.InsertAction.ItemIndex} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Item item = 1;
 * @return {proto.ProtobufHistory.Item}
 */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.getItem = function() {
  return /** @type{proto.ProtobufHistory.Item} */ (
    jspb.Message.getWrapperField(this, geometry_item_pb.Item, 1));
};


/** @param {proto.ProtobufHistory.Item|undefined} value  */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.setItem = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ProtobufHistory.InsertAction.ItemIndex.prototype.clearItem = function() {
  this.setItem(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.hasItem = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Index index = 2;
 * @return {proto.Index}
 */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.getIndex = function() {
  return /** @type{proto.Index} */ (
    jspb.Message.getWrapperField(this, geometry_index_pb.Index, 2));
};


/** @param {proto.Index|undefined} value  */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.setIndex = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ProtobufHistory.InsertAction.ItemIndex.prototype.clearIndex = function() {
  this.setIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.InsertAction.ItemIndex.prototype.hasIndex = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.RemoveAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.RemoveAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.RemoveAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.RemoveAction.displayName = 'proto.ProtobufHistory.RemoveAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.RemoveAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.RemoveAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.RemoveAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.RemoveAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.RemoveAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.ProtobufHistory.RemoveAction.ItemIndex.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.RemoveAction} The clone.
 */
proto.ProtobufHistory.RemoveAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.RemoveAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated ItemIndex items = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ProtobufHistory.RemoveAction.ItemIndex>}
 */
proto.ProtobufHistory.RemoveAction.prototype.getItemsList = function() {
  return /** @type{!Array.<!proto.ProtobufHistory.RemoveAction.ItemIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ProtobufHistory.RemoveAction.ItemIndex, 1));
};


/** @param {Array.<!proto.ProtobufHistory.RemoveAction.ItemIndex>} value  */
proto.ProtobufHistory.RemoveAction.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.RemoveAction.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.RemoveAction.ItemIndex = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ProtobufHistory.RemoveAction.ItemIndex, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.RemoveAction.ItemIndex.displayName = 'proto.ProtobufHistory.RemoveAction.ItemIndex';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.RemoveAction.ItemIndex.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.RemoveAction.ItemIndex} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.RemoveAction.ItemIndex.toObject = function(includeInstance, msg) {
  var f, obj = {
    item: (f = msg.getItem()) && geometry_item_pb.Item.toObject(includeInstance, f),
    index: (f = msg.getIndex()) && geometry_index_pb.Index.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.RemoveAction.ItemIndex} The clone.
 */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.RemoveAction.ItemIndex} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Item item = 1;
 * @return {proto.ProtobufHistory.Item}
 */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.getItem = function() {
  return /** @type{proto.ProtobufHistory.Item} */ (
    jspb.Message.getWrapperField(this, geometry_item_pb.Item, 1));
};


/** @param {proto.ProtobufHistory.Item|undefined} value  */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.setItem = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.clearItem = function() {
  this.setItem(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.hasItem = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Index index = 2;
 * @return {proto.Index}
 */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.getIndex = function() {
  return /** @type{proto.Index} */ (
    jspb.Message.getWrapperField(this, geometry_index_pb.Index, 2));
};


/** @param {proto.Index|undefined} value  */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.setIndex = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.clearIndex = function() {
  this.setIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.RemoveAction.ItemIndex.prototype.hasIndex = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.GroupAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.GroupAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.GroupAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.GroupAction.displayName = 'proto.ProtobufHistory.GroupAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.GroupAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.GroupAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.GroupAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.GroupAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.GroupAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    childindexesList: jspb.Message.toObjectList(msg.getChildindexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    groupindex: (f = msg.getGroupindex()) && geometry_index_pb.Index.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.GroupAction} The clone.
 */
proto.ProtobufHistory.GroupAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.GroupAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index childIndexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.GroupAction.prototype.getChildindexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.GroupAction.prototype.setChildindexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.GroupAction.prototype.clearChildindexesList = function() {
  this.setChildindexesList([]);
};


/**
 * optional Index groupIndex = 2;
 * @return {proto.Index}
 */
proto.ProtobufHistory.GroupAction.prototype.getGroupindex = function() {
  return /** @type{proto.Index} */ (
    jspb.Message.getWrapperField(this, geometry_index_pb.Index, 2));
};


/** @param {proto.Index|undefined} value  */
proto.ProtobufHistory.GroupAction.prototype.setGroupindex = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ProtobufHistory.GroupAction.prototype.clearGroupindex = function() {
  this.setGroupindex(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.GroupAction.prototype.hasGroupindex = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.UngroupAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProtobufHistory.UngroupAction.repeatedFields_, null);
};
goog.inherits(proto.ProtobufHistory.UngroupAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.UngroupAction.displayName = 'proto.ProtobufHistory.UngroupAction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProtobufHistory.UngroupAction.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.UngroupAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.UngroupAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.UngroupAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.UngroupAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    childindexesList: jspb.Message.toObjectList(msg.getChildindexesList(),
    geometry_index_pb.Index.toObject, includeInstance),
    groupindex: (f = msg.getGroupindex()) && geometry_index_pb.Index.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.UngroupAction} The clone.
 */
proto.ProtobufHistory.UngroupAction.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.UngroupAction} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Index childIndexes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Index>}
 */
proto.ProtobufHistory.UngroupAction.prototype.getChildindexesList = function() {
  return /** @type{!Array.<!proto.Index>} */ (
    jspb.Message.getRepeatedWrapperField(this, geometry_index_pb.Index, 1));
};


/** @param {Array.<!proto.Index>} value  */
proto.ProtobufHistory.UngroupAction.prototype.setChildindexesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.ProtobufHistory.UngroupAction.prototype.clearChildindexesList = function() {
  this.setChildindexesList([]);
};


/**
 * optional Index groupIndex = 2;
 * @return {proto.Index}
 */
proto.ProtobufHistory.UngroupAction.prototype.getGroupindex = function() {
  return /** @type{proto.Index} */ (
    jspb.Message.getWrapperField(this, geometry_index_pb.Index, 2));
};


/** @param {proto.Index|undefined} value  */
proto.ProtobufHistory.UngroupAction.prototype.setGroupindex = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ProtobufHistory.UngroupAction.prototype.clearGroupindex = function() {
  this.setGroupindex(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.UngroupAction.prototype.hasGroupindex = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.ProtobufHistory);
