/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var history_frame_pb = require('../history/frame_pb.js');
goog.exportSymbol('proto.ProtobufHistory.DocHistory', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProtobufHistory.DocHistory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ProtobufHistory.DocHistory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProtobufHistory.DocHistory.displayName = 'proto.ProtobufHistory.DocHistory';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProtobufHistory.DocHistory.prototype.toObject = function(opt_includeInstance) {
  return proto.ProtobufHistory.DocHistory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProtobufHistory.DocHistory} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ProtobufHistory.DocHistory.toObject = function(includeInstance, msg) {
  var f, obj = {
    initial: (f = msg.getInitial()) && history_frame_pb.HistoryFrame.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.ProtobufHistory.DocHistory} The clone.
 */
proto.ProtobufHistory.DocHistory.prototype.cloneMessage = function() {
  return /** @type {!proto.ProtobufHistory.DocHistory} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional HistoryFrame initial = 1;
 * @return {proto.ProtobufHistory.HistoryFrame}
 */
proto.ProtobufHistory.DocHistory.prototype.getInitial = function() {
  return /** @type{proto.ProtobufHistory.HistoryFrame} */ (
    jspb.Message.getWrapperField(this, history_frame_pb.HistoryFrame, 1));
};


/** @param {proto.ProtobufHistory.HistoryFrame|undefined} value  */
proto.ProtobufHistory.DocHistory.prototype.setInitial = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ProtobufHistory.DocHistory.prototype.clearInitial = function() {
  this.setInitial(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.ProtobufHistory.DocHistory.prototype.hasInitial = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.ProtobufHistory);
